version: "3.8"
services:
  mongodb-todolist:
    image : mongo
    container_name: mongodb-todolist
    volumes:
      - database:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  database: